app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('chatbot/', views.room, name='room'),
    path('marketplace/', views.home, name='home'),
    
    path('', views.placements, name='placements'),
    path('marketplace/<placement_slug>/', views.placement_detail, name='placement-detail'),

    path('my-bids/', views.bid_summary, name='bid-summary' ),
    path('confirm-bids/', views.confirm_bids, name='confirm-bids'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('about/', views.about, name='about'),
    
    path("Seller_profile/",views.Seller_profile, name="Seller_profile")

]

bidding_system/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app'))
]

app/templates/Seller_profile.html
{% extends 'base.html' %} {% block content %} {% include 'nav.html' %} {% load static %}

<div class="container mt-5">
    
  <div class="row d-flex justify-content-center">
      
      <div class="col-md-7">
          
          <div class="card p-3 py-4">
              
              <div class="text-center">
                  <img src="https://media-exp1.licdn.com/dms/image/C4D03AQF6ZD3XUheUxQ/profile-displayphoto-shrink_100_100/0/1650766729100?e=1661385600&v=beta&t=yNMe5StARHBoUzoZlsHZQdvQ5gSDC8KB14uWpm6Lxl8" width="150" height="150" class="rounded-circle" >
              </div>
              
              <div class="text-center mt-3">
                  
                  <h5 class="mt-2 mb-0">Hafiz Zeeshan Naseer</h5>
                  <span>Product Seller</span>
                  
                  <div class="px-4 mt-1">
                      <p class="fonts">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
                  
                  </div>
                  
                   <ul class="social-list">
                      <li><i class="fa fa-facebook"></i></li>
                      <li><i class="fa fa-dribbble"></i></li>
                      <li><i class="fa fa-instagram"></i></li>
                      <li><i class="fa fa-linkedin"></i></li>
                      <li><i class="fa fa-google"></i></li>
                  </ul>
                  
                  <div class="buttons">
                      
                      <button class="btn btn-outline-primary px-4">Message</button>
                      <button class="btn btn-primary px-4 ms-3">Contact</button>
                      <br><br><br><br><br>
                  </div>
                  
                  
              </div>
              
             
              
              
          </div>
          
      </div>
      
  </div>
  
</div>












{% include 'footer.html' %} {% endblock content %}

app/templates/about.html
{% extends 'base.html' %} {% block content %} {% include 'nav.html' %}

<section class="section">
    <section class="container">

        <article class="card">
            <div class="card-content">
                <h3><center>About</center></h3>
                <p class="custom-font-1">A bidding system in contract bridge is the set of agreements and understandings assigned to calls and sequences of calls used by a partnership, and includes a full description of the meaning of each treatment and convention</p>
</div>
        </article>
        <article class="card">
            <div class="card-content">
                <h3><center>Available Routes</center></h3>
                <ul class="collection custom-font-1">
                    <li class="collection-item"><span class="chip">/</span> The home page. Contains new Products.</li>
                    <li class="collection-item"><span class="chip">about/</span> Holds details about the application.</li>
                    <li class="collection-item"><span class="chip">register/</span> Allows users to register an account</li>
                    <li class="collection-item"><span class="chip">login/</span> Allows users to login to an account</li>
                    <li class="collection-item"><span class="chip">logout/</span> Allows users to logout and clear their session</li>
                    <li class="collection-item"><span class="chip">dashboard/</span> Data analytics and animated charts for the database.</li>
                    <li class="collection-item"><span class="chip">chatbot/</span> Integarated chatbot Chatbot.</li>


                </ul>
            </div>
        </article>


        <article class="card">
            <div class="card-content">
                <h3><center>Features and specs</center></h3>
                <ul class="collection custom-font-1">
                    <li class="collection-item">Authentication system - users can login, register and logout, passwords.</li>
                    <li class="collection-item ">Certain routes are protected with a login required.</li>
                    <li class="collection-item">App uses materialize css framework borrowing from Google's material design principles</li>
                    <li class="collection-item">App developed mainly in Django framework and Javascript.</li>
                </ul>
            </div>
        </article>

    </section>
</section>

{% include 'footer.html' %} {% endblock content %}

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <link href="https://fonts.googleapis.com/css?family=Literata|Raleway|Montserrat|Nunito&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicon/apple-icon-60x60.png' %}' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/manifest.json' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>The Bidding Store</title>

    <style>
      p {
        margin-top: 0.5rem !important;
        margin-bottom: 0.5rem!important;
      }
       .responsive {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 70%;
      }
.grid{
  display:grid;
  grid-template-columns: 300px 300px 300px ;
  grid-column-gap:80px;
  margin-left: 0px;
}

.card-product{
  width:450px;
  height:350px;
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 300px;
  margin: auto;
  margin-top: 50px;
  text-align: center;
  font-family: arial;
  margin-bottom: 10px;
  margin-left: 30px;
  border-radius: 30px;
  border: 1px solid #7f7a80;
  transition: transform .2s;
}

.card-product:hover{
  transform: scale(1.15);
  background-color:#C1DBF1;
  color:black;
}

.card-content1{
  height:200px;
  text-align:center;
  border:1px solid #7f7a80;
}

.card-content:hover{
  border: 1px solid #7f7a80;
  background-color: #C1DBF1;
  color:black;
}


      img {
        margin-top: 1em;
        padding: 4%;
      }

      .custom-font-1 {
        font-family: 'Literata', serif;
      } 

       h2, h3, h4, h5, h6 {
        margin-top: .5em !important;
        font-family: 'Nunito', sans-serif;
        font-weight: bold;
      }

      body {
        display: flex;
        min-height: 100vh;
        flex-direction: column;
      }

      main {
        flex: 1 0 auto;
      }
        
      input:focus {
        border-bottom: 1px solid deeppink !important;
        box-shadow: 0 1px 0 0 deeppink !important;
      }
      
      .card-text{
         text-align:center;
      }

      .fa {
        padding: 20px;
        font-size: 30px;
        width: 100px;
        text-align: center;
        text-decoration: none;
        margin: 5px 2px;
      }


.fa:hover {
  opacity: 0.7;
}

.fa-facebook {
background: #3B5998;
color: white;
}

.fa-twitter {
background: #55ACEE;
color: white;
}


      /* ----------------------------------------------
 * Generated by Animista on 2019-7-21 13:37:41
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

.fade-in {
	-webkit-animation: fade-in 1s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	        animation: fade-in 1s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}

{% comment %} Admin Profit CSS {% endcomment %}

body{
  background:#eee;
}

.card{
  border:none;
  position:relative;
  overflow:hidden;
  border-radius:8px;
  cursor:pointer;
}

.card:before{
  
  content:"";
  position:absolute;
  left:0;
  top:0;
  width:4px;
  height:100%;
  background-color:#E1BEE7;
  transform:scaleY(1);
  transition:all 0.5s;
  transform-origin: bottom
}

.card:after{
  
  content:"";
  position:absolute;
  left:0;
  top:0;
  width:4px;
  height:100%;
  background-color:#8E24AA;
  transform:scaleY(0);
  transition:all 0.5s;
  transform-origin: bottom
}

.card:hover::after{
  transform:scaleY(1);
}


.fonts{
  font-size:11px;
}

.social-list{
  display:flex;
  list-style:none;
  justify-content:center;
  padding:0;
}

.social-list li{
  padding:10px;
  color:#8E24AA;
  font-size:19px;
}


.buttons button:nth-child(1){
     border:1px solid #8E24AA !important;
     color:#8E24AA;
     height:40px;
}

.buttons button:nth-child(1):hover{
     border:1px solid #8E24AA !important;
     color:#fff;
     height:40px;
     background-color:#8E24AA;
}

.buttons button:nth-child(2){
     border:1px solid #8E24AA !important;
     background-color:#8E24AA;
     color:#fff;
      height:40px;
}

    </style>
</head>
<body class="grey lighten-4">
    {% block content %}
    {% endblock content %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
    document.addEventListener('DOMContentLoaded', function(){
      var elems = document.querySelectorAll('.sidenav');
      var instances = M.Sidenav.init(elems);
    })
    </script>
</body>
</html>

app/templates/bid-summary.html
{% extends 'base.html' %}

{% block content %}
{% include 'nav.html' %}

<section class="section">
    <section class="container">
        <div class="card">
            <div class="card-content">
                <h4>Your bid summary</h4>
                <table class="table responsive-table">
                    <thead>
                        <tr>
                            <th>Brand Name</th>
                            <th>Timestamp</th>
                            <th>$ Bidded</th>
                            <th>Quantity</th>
                            <th>Seller Details</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for b in bids %}
                            <tr>
                                <td>{{ b.placement.placement_company }}</td>
                                <td>{{ b.placementbid_created }}</td>
                                <td>{{ b.offer}}</td>
                                <td>{{ b.shares}}</td>
                                <td>{% if b.confirmed %}<a href="{% url 'app:Seller_profile' %}" style="margin-top: 1rem;" ><span class="chip indigo light-2 white-text">Confirmed Bid</span>       </a>{%else%} <span class="chip indigo light-2 white-text">Unconfirmed</span>       {%endif%} </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

                {% comment %} <a href="{% url 'app:confirm-bids' %}" style="margin-top: 1rem;" class="btn waves-light waves-effect pink">Confirm Bids</a> {% endcomment %}
            </div>
        </div>

    </section>
</section>

{% include 'footer.html' %}
{% endblock content %}

app/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
{% include 'nav.html' %}

              
{% load static %}

<section class="section">
    <section class="container">
        <section class="row">
            <div class="col l3 s12">
                <div class="card">
                    <div class="card-content center">
                        <p class="chip">Registered Users</p>
                        <h4 id="total_users"></h4>
                    </div>
                </div>
            </div>
            <div class="col l3 s12">
                <div class="card">
                        <div class="card-content center">
                                <p class="chip">Total Brands</p>
                                <h4 id="total_companies"></h4>
                            </div>
                </div>
            </div>
            <div class="col l3 s12">
                <div class="card">
                        <div class="card-content center">
                                <p class="chip">Total Bids</p>
                                <h4><span id="total_offers"></span></h4>
                            </div>
                </div>
            </div>
            <div class="col l3 s12">
                    <div class="card">
                    <div class="card-content center">
                            <p class="chip">Total Products</p>
                            <h4 id="total_placements"></h4>
                        </div>
                    </div>
                </div>
        </section>

        <section class="row">
            <div class="col l12 s12">
                <div class="card">
                    <div class="card-content center">
                            <h5>Top 5 placements by $</h5>
                            <canvas id="myChart"></canvas>
                    </div>
                </div>
            </div>
        </section>
    </section>
</section>

{% include 'footer.html' %}

<script>
// Number Incrementer function 
// from https://stackoverflow.com/questions/16994662/count-animation-from-number-a-to-b
function animateValue(id, start, end, duration) {
    var range = end - start;
    var current = start;
    var increment;
    var increment = end > start? 1 : -1;
    var stepTime = Math.abs(Math.floor(duration / range));
    var obj = document.getElementById(id);
    var timer = setInterval(function() {
        current += increment;
        obj.innerText = current;
        if (current == end) {
            clearInterval(timer);
        }
    }, stepTime);
}

animateValue("total_companies", 0, {{ total_companies }}, 1750);
animateValue("total_placements", 0, {{ total_placements }}, 1750);
animateValue("total_users", 0, {{ total_users }}, 1750);
animateValue("total_offers", 0, {{ total_offers }}, 500);
</script>
<script>
        // Chart.js code
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'horizontalBar',
            data: {
                labels: {{ top_5_offer_names|safe }},
                datasets: [{
                    label: 'Amount $',
                    data:{{ top_5_offer_values|safe }},
                    backgroundColor: 'rgba(48, 63, 159, 1)',
                    borderWidth: 0.5
                }]
            },
            options: {
                legend: {
                    display: true
                },
                scales: {
                    yAxes: [{
                        gridLines: {display:true},
                        ticks: {
                            beginAtZero: true,
                            maxTicksLimit: 5
                        }
                    }],
                    xAxes: [{
                        gridLines: {display:true,  color:'#F5F5F2'},
                        ticks: {
                            beginAtZero: true,
                            maxTicksLimit: 6
                        }
                    }]
                }
            }
        });
        </script>

{% endblock content %}

app/templates/home.html
{% extends 'base.html' %}

{% block content %}
{% include 'nav.html' %}

              
{% load static %}

<section class="section">
    <section class="container">
        
            <div class="col s12">
                    <div class="card">
                            <div class="card-content1">
                                <h3><center>Welcome to the Bidding Store</center></h3>
                                <p><center>Explore Products by various listed Brands</center></p>
                                
                            </div>
                        </div>
            </div>
                                    <div class="grid" >
                                        {%for p in placements %}
                                        
                                      
                                        <div class="card-product">
                                            <div class="image_image">
                                              
                                                 <img src="{{ p.picture.url }}" class="responsive" height="180" width="200"/>
                                               
                                            </div>
                                            <div class="card-body">
                                                <div class="container">
                                                <p><b>Bid price : {{ p.price }}$</b></p>
                                               <p> Total Quantity : {{ p.total_pieces }}</p>
                                                </div>
                                              <a href="{% url 'app:placement-detail' p.placement_slug %}" style="margin-top: 1rem;" class="btn blue waves-effect waves-light">View Details</a>
                                            </div>
                                        </div>
                                   
                                      
                                        {% endfor %}
                                    </div>

                            <ul class="pagination center">
                                {% if placements.has_previous %}
                                <li class="waves-effect"><a href="?page={{placements.previous_page_number}}">{{ placements.previous_page_number}}</a></li>
                                {% endif %}

                                <li class="active indigo"><a href="#!">{{placements.number}}</a></li>
                               
                                {% if placements.has_next %}
                                <li class="waves-effect"><a href="?page={{placements.next_page_number}}">{{ placements.next_page_number}}</a></li>
                                {% endif %}
                            </ul>
                                            
                </div>
            </div>

    </section>
</section>

{% include 'footer.html' %}
{% endblock content %}

app/templates/login.html
{% extends 'base.html' %} {% block content %}
<main>
    <section class="section">
        <section class="container">
            <div class="row">
                <div class="col l8 m12 s12">
                    <div class="card">
                        <div class="card-content">
                            <form action="" method="POST" class="form">
                                {% csrf_token %}
                                <h5>Login page</h5>
                                <div class="input-field">
                                    <label for="" class="label">
                                        Username
                                    </label>
                                    <input type="text" name="username">
                                </div>
                                <div class="input-field">
                                    <label for="" class="label">
                                        Password
                                    </label>
                                    <input type="password" name="password">
                                </div>
                                <div class="input-field">
                                    <button style="margin-top: 1rem;" class="btn waves-effect waves-light pink" type="submit">Login</button>
                                </div>
                                <p>Don't have an account? click <a href="{% url 'app:register' %}" style="margin-top: 1rem;" type="a">here</a> to register.</p>
                            </form>
                        </div>
                    </div>

                </div>
            </div>

        </section>

    </section>
</main>
{% include 'footer.html' %} {% endblock content %}

app/templates/nav.html
<nav>
<div class="nav-wrapper indigo darken-2">
    <div class="container">
    <!-- <a href="{% url 'app:home' %}" class="brand-logo" style="font-size: 1.3rem;">
       <strong>BIDDING PLATFORM</strong></a> -->
    <a href="#" data-target="mobile-demo" class="sidenav-trigger waves-effect waves-light"><i class="material-icons">menu</i></a>
    <ul class="left hide-on-med-and-down">
        <li><a href="{% url 'app:placements' %}"><i class="material-icons">home</i></a></li>
        <li><a href="{% url 'app:room' %}"><i class="material-icons">store</i></a></li>
        <li><a href="{% url 'app:bid-summary' %}"><i class="material-icons">view_list</i></a></li>
        <li><a href="{% url 'app:about' %}"><i class="material-icons">help</i></a></li>
        <li><a href="{% url 'app:dashboard' %}"><i class="material-icons">insert_chart</i></a></li>
        
    </ul>

    <ul class="right hide-on-med-and-down">
            {% if user.is_authenticated %}
            <li><a class="btn-small waves-effect waves-light grey darken-4" href="{% url 'app:logout' %}">Logout</a></li>
            <li>Logged in as <strong>{{ user.username }}</strong></li>
        {% else %}
        <li>
            <a class="btn-small waves-effect waves-light pink" href="{% url 'app:register' %}">
                Register
            </a>
            </li>
        <li>
            <a class="btn-small waves-effect waves-light pink" href="{% url 'app:login' %}">
                Login
            </a>
        </li>
        {% endif %}
    </ul>
</div>
</div>
</nav>

<ul class="sidenav" id="mobile-demo">
    <li><a href="{% url 'app:placements' %}"><i class="material-icons">home</i>Home</a></li>
    <li><a href="{% url 'app:room' %}"><i class="material-icons">store</i>Products</a></li>
    <li><a href="{% url 'app:bid-summary' %}"><i class="material-icons">view_list</i>My Bids</a></li>
    <li><a href="{% url 'app:about' %}"><i class="material-icons">assignment</i>About</a></li>
    <li><a href="{% url 'app:dashboard' %}"><i class="material-icons">insert_chart</i>Analytics</a></li>
    {% if user.is_authenticated %}
        <li><a class="btn-small waves-effect waves-light grey darken-4" href="{% url 'app:logout' %}">Logout</a></li>
    {% else %}
    <li><a class="btn-small waves-effect waves-light pink" href="{% url 'app:register' %}">
        Register</a>
    </li>
    <li><a class="btn-small waves-effect waves-light pink" href="{% url 'app:login' %}">
        Login</a>
    </li>
    {% endif %}
</ul>

app/templates/placements.html
{% extends 'base.html' %}

{% block content %}
{% include 'nav.html' %}

              
{% load static %}

<section class="section">
    <section class="container">
        
            <div class="col s12">
                    <div class="card">
                            <div class="card-content1">
                                <h3><center>Welcome to the Bidding Store</center></h3>
                                <p><center>Explore Products by various listed Brands</center></p>
                                
                            </div>
                        </div>
            </div>
                                    <div class="grid" >
                                        {%for p in placements %}
                                        
                                      
                                        <div class="card-product">
                                            <div class="image_image">
                                              
                                                 <img src="{{ p.picture.url }}" class="responsive" height="180" width="200"/>
                                               
                                            </div>
                                            <div class="card-body">
                                                <div class="container">
                                                <p><b>Bid price : {{ p.price }}$</b></p>
                                               <p> Total Quantity : {{ p.total_pieces }}</p>
                                                </div>
                                              <a href="{% url 'app:placement-detail' p.placement_slug %}" style="margin-top: 1rem;" class="btn blue waves-effect waves-light">View Details</a>
                                            </div>
                                        </div>
                                   
                                      
                                        {% endfor %}
                                    </div>

                            <ul class="pagination center">
                                {% if placements.has_previous %}
                                <li class="waves-effect"><a href="?page={{placements.previous_page_number}}">{{ placements.previous_page_number}}</a></li>
                                {% endif %}

                                <li class="active indigo"><a href="#!">{{placements.number}}</a></li>
                               
                                {% if placements.has_next %}
                                <li class="waves-effect"><a href="?page={{placements.next_page_number}}">{{ placements.next_page_number}}</a></li>
                                {% endif %}
                            </ul>
                                            
                </div>
            </div>

    </section>
</section>

{% include 'footer.html' %}
{% endblock content %}

app/templates/register.html
{% extends 'base.html' %} {% block content %}
<main>
    <section class="section">
        <section class="container">
            <div class="row">
                <div class="col l12 s12">
                    <div class="card">
                        <div class="card-content">
                            <form action="" method="POST" class="form">
                                {% csrf_token %}
                                <h5>Registration</h5>
                                {{ form.as_p }}
                                <div class="center">
                                    <button style="margin-top: 1rem;" class="btn pink waves-effect waves-light" type="submit">Create Account</button>
                                </div>
                                <a href="{% url 'app:home' %}" style="margin-top: 1rem;">Go back to home page.</a>

                            </form>
                            
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </section>
</main>
{% include 'footer.html' %} {% endblock content %}